### ISSUE TITLE
Update URI to Lowell Asteroid database in perl script

### ISSUE THREAD

**Issue by rmathar** [XEphem/XEphem#29]
The scheme part ```ftp:``` string in lines 12, 66, 120, 236, 237 of ```GUI/xephem/auxil/astorb2edb.pl ``` should be changed to ```https:```. The leading ```ftp``` in the "authority" of the URI itself, that means in ```ftp.lowell.edu```, should not be changed.

In line 33 the ```1.7 Mb``` should be changed to ```83 MB``` and in line 34 the ```6.3 Mb``` to ```305 MB```.

Perhaps one should also change in line 237 the ```clearskyinstitute.com``` as the user address to github.com (?)

**Comment by brandon-rhodes** [comment]
Thanks for the pull request! I've committed your changes (hopefully correctly; git sometimes confuses me!) as:

aaaea1edc5783fc30906ecd17ef7d4a4f3cc00cd

Please comment if it looks like I applied any of the changes incorrectly.
