### ISSUE TITLE
Update the documentation: Install on Ubuntu/Mint needs libssl-dev

### ISSUE THREAD

**Issue by djtrustgod** [XEphem/XEphem#43]
When building Xephem 4.1.0 on Linux Mint 20.2, make received fatal error "openssl/sha.h: No such file or directory"

This was fixed by installing libssl-dev
sudo apt-get install libssl-dev

Please update the INSTALL readme file to indicate the need to install this library on Debian/Ubuntu distributions.

**Comment by brandon-rhodes** [comment]
Happily, the INSTALL file was recently updated:

https://github.com/XEphem/XEphem/blob/main/INSTALL#L18

The new text should appear in the next release of XEphem.
