### ISSUE TITLE
Site?

### ISSUE THREAD

**Issue by zvezdochiot** [XEphem/XEphem#44]
Maybe replace:
```ls
bg.png
binary.png
binary-tn.png
C2009P1.gif
coordsysbutton.gif
CSI-xs.png
data.png
earthsat.png
earthsat-tn.png
earthwx.gif
earthwx-tn.gif
gridbutton.gif
HSTOrbitAnim.gif
INDI.png
INDI-tn.png
intro-hzn.png
intro-moon.png
jupiter.png
jupiter-tn.gif
main.png
mars.png
mars-tn.png
moon.png
moon-tn.gif
naag.gif
naag-tn.gif
obslog.png
osxshot.png
plot.png
plot-tn.gif
SatMovie.gif
saturn.png
saturn-tn.png
skyip.gif
skyip-tn.gif
skyview.png
skyview-tn.gif
solsys.gif
solsys-tn.gif
sun.png
sun-tn.png
uranus.gif
uranus-tn.gif
wcs.gif
wcs-tn.gif
webmenu.png
xephemdrop.png
xephem.png
```
to `XEphem/Site/img`?

[XEphem.diff.gz](https://github.com/XEphem/XEphem/files/7619390/XEphem.diff.gz)

**Comment by brandon-rhodes** [comment]
Are the images causing any problems that we could resolve some other way? I would prefer to leave them in place so that any external links to them can remain stable. I do see your diff that tries to fix all of the internal references to them; but it also seems to make other adjustments to the HTML?

**Comment by zvezdochiot** [comment]
@brandon-rhodes say:
>Are the images causing any problems that we could resolve some other way?

No problem, I just don't like the mess.
