### ISSUE TITLE
[request] Fedora 38 RPM build

### ISSUE THREAD

**Issue by runlevel5** [XEphem/XEphem#79]
Dear @rmathar 

Could you please build RPM packages for Fedora 38 too?

Great thanks in advance

**Comment by rmathar** [comment]
The natural place to search for the Fedora package is
https://packages.fedoraproject.org/search?query=xephem
rather than the openSUSE build project, where the RPM package for Fedora 38 seems to exist. Anyway I've added a build to the openSUSE project as an alternative.

**Comment by brandon-rhodes** [comment]
@rmathar — But, having just re-read the refusal: XEphem is now under the MIT license, which is at the root of the repo.

Let me guess: did I fail to update the documentation and/or the in-app “About” window to replace the old educational-use-only license with the more up-to-date MIT license?

**Comment by brandon-rhodes** [comment]
Oh, yeah, look at that — the wiki mostly dates from the twenty-aughts. I'll ignore it, then.
