### ISSUE TITLE
Request for Code Documentation

### ISSUE THREAD

**Issue by rishitc** [XEphem/XEphem#8]
Hi,
I'm want to get involved in contributing to XEphem.
I read up about the software on your website and I was really interested in learning more about it.

I wanted to know of there was any **formal documentation** that one can follow to understand the code and work on adding features/improvements to it?

Thanks

**Comment by brandon-rhodes** [comment]
Welcome! No, I don’t think there is any formal documentation. But please feel free to comment with a list of the kinds of questions you have that such documentation could answer — we could gradually collect answers to them and use those answers to create such a document.

**Comment by rishitc** [comment]
Hi,
I feel that the first step should be to **document the interfaces** that are offered by each of the library files.
That would help in understanding which parts of the library are for use by external programs, and which parts of the library are implementation details.

If we know the interfaces available, it should be possible to work backwards and understand what the code is trying to do to a reasonable extent.

**Comment by rishitc** [comment]
Hi,
Is it possible to discuss with the original code authors about the different interfaces in the code? I think that discussions with the original authors would be helpful in starting the process of code documentation.

**Comment by brandon-rhodes** [comment]
My impression is that the original author now considers their work finished, and is not planning on further contributions, but of course I can’t myself speak on their behalf. Would it be possible for you to specific about which routine in the code you are finding confusing, or what you are trying to accomplish? My limited dives into the code suggested a fairly clean division between `libastro` and the GUI code above it.

**Comment by rishitc** [comment]
The ```libastro``` library is quite well commented, with references to the sources for the formulas implemented, though I do feel that some of the sources mentioned in the comments are slightly difficult to find online, but checking Wikipedia in those cases was helpful.

**Comment by rishitc** [comment]
Will have to check out the GUI code soon, to better understand how it works.
Can I post any questions, I may have about the GUI code, in this thread?

**Comment by brandon-rhodes** [comment]
Would it make more sense for us to create a Discussion for that purpose over in the Discussions section instead? That would keep the list of Issues more focused on things like bugs or code upgrades that are immediately actionable.

**Comment by rishitc** [comment]
Sure, let's do that.

**Comment by brandon-rhodes** [comment]
Pending creation of the Discussion, I'm going ahead and closing this to keep the list of Issues focused. Thanks!

**Comment by rishitc** [comment]
Thanks for closing this issue! I have not yet been able to review the source code completely. I plan to review it at least once before starting the discussion. Till where I have reached, the code is quite interesting and I definitely want to finish reading it.
