### ISSUE TITLE
Updating the "Download..." urls

### ISSUE THREAD

**Issue by olav6** [XEphem/XEphem#80]
These revised urls worked for me in XEphem 4.1.0:

https://celestrak.org/NORAD/elements/stations.txt
https://celestrak.org/NORAD/elements/science.txt
https://celestrak.org/NORAD/elements/tle-new.txt
https://celestrak.org/NORAD/elements/amateur.txt
https://celestrak.org/NORAD/elements/visual.txt

**Comment by dave-kaye** [comment]
Please close this issue as the code has been modified and merged.

**Comment by brandon-rhodes** [comment]
Well, drat. The commit message "Closes issue #80" apparently doesn't work! I should have been more brief and edited it to say "Closes #80". Thanks for pointing out that it didn't cause an automatic close.
