### ISSUE TITLE
README.md pointer to Fedora packages

### ISSUE THREAD

**Issue by rmathar** [XEphem/XEphem#84]
The ``README.md`` file in https://github.com/XEphem/XEphem
points for Ubuntu, Fedora and CentOS to
https://build.opensuse.org/package/show/home:rjmathar/xephem  .
The Fedora link should point to  https://packages.fedoraproject.org/pkgs/xephem/xephem/
instead, because on that operating system the packages has an
official maintainer.

**Comment by brandon-rhodes** [comment]
Thanks for pointing out that there was a better link available! I've updated the README.
